name: j_util
description: Misc. utilities
version: 2.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  archive: ^3.6.1
  collection: ^1.18.0
  flutter:
    sdk: flutter
  http: ^1.2.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  oauth2: ^2.0.2
  webview_flutter: ^4.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.25.2