name: j_util
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  oauth2: ^2.0.2
  webview_flutter: ^4.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
